<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/** The format of the response. */
enum Format: string
{
    case Token = 'token';
    case Cookie = 'cookie';
}
