<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class RefreshSessionRequest
{
    /**
     * The ID of the session
     *
     * @var string $sessionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=session_id')]
    public string $sessionId;

    /**
     * Refresh session parameters
     *
     * @var ?RefreshSessionRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?RefreshSessionRequestBody $requestBody = null;

    /**
     * @param  string  $sessionId
     * @param  ?RefreshSessionRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $sessionId, ?RefreshSessionRequestBody $requestBody = null)
    {
        $this->sessionId = $sessionId;
        $this->requestBody = $requestBody;
    }
}