<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** AccountlessApplication - Success */
class AccountlessApplication
{
    /**
     *
     * @var AccountlessApplicationObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\AccountlessApplicationObject')]
    public AccountlessApplicationObject $object;

    /**
     *
     * @var string $publishableKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('publishable_key')]
    public string $publishableKey;

    /**
     *
     * @var ?string $secretKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('secret_key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $secretKey = null;

    /**
     *
     * @var ?string $claimUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('claim_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $claimUrl = null;

    /**
     *
     * @var ?string $apiKeysUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('api_keys_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $apiKeysUrl = null;

    /**
     * @param  AccountlessApplicationObject  $object
     * @param  string  $publishableKey
     * @param  ?string  $secretKey
     * @param  ?string  $claimUrl
     * @param  ?string  $apiKeysUrl
     * @phpstan-pure
     */
    public function __construct(AccountlessApplicationObject $object, string $publishableKey, ?string $secretKey = null, ?string $claimUrl = null, ?string $apiKeysUrl = null)
    {
        $this->object = $object;
        $this->publishableKey = $publishableKey;
        $this->secretKey = $secretKey;
        $this->claimUrl = $claimUrl;
        $this->apiKeysUrl = $apiKeysUrl;
    }
}