<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


enum AccountlessApplicationObject: string
{
    case AccountlessApplication = 'accountless_application';
}
