<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Cookies
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     * @var CookiesObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CookiesObject')]
    public CookiesObject $object;

    /**
     * Array of cookie directives.
     *
     * @var array<string> $cookies
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cookies')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $cookies;

    /**
     * @param  CookiesObject  $object
     * @param  array<string>  $cookies
     * @phpstan-pure
     */
    public function __construct(CookiesObject $object, array $cookies)
    {
        $this->object = $object;
        $this->cookies = $cookies;
    }
}