<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** String representing the object's type. Objects of the same type share the same value. */
enum CookiesObject: string
{
    case Cookies = 'cookies';
}
