<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class ExternalAccountWithVerification
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     * @var ExternalAccountWithVerificationObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ExternalAccountWithVerificationObject')]
    public ExternalAccountWithVerificationObject $object;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $provider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider')]
    public string $provider;

    /**
     *
     * @var string $identificationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identification_id')]
    public string $identificationId;

    /**
     * The unique ID of the user in the external provider's system
     *
     * @var string $providerUserId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider_user_id')]
    public string $providerUserId;

    /**
     *
     * @var string $approvedScopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('approved_scopes')]
    public string $approvedScopes;

    /**
     *
     * @var string $emailAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email_address')]
    public string $emailAddress;

    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    public string $lastName;

    /**
     * $publicMetadata
     *
     * @var array<string, mixed> $publicMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('public_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>')]
    public array $publicMetadata;

    /**
     * Unix timestamp of creation
     *
     *
     *
     * @var int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * Unix timestamp of creation
     *
     *
     *
     * @var int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public int $updatedAt;

    /**
     * Please use `image_url` instead
     *
     * @var ?string $avatarUrl
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('avatar_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $avatarUrl = null;

    /**
     *
     * @var Oauth|GoogleOneTap|null $verification
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verification')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Oauth|\Clerk\Backend\Models\Components\GoogleOneTap|null')]
    public Oauth|GoogleOneTap|null $verification;

    /**
     * $additionalProperties
     *
     * @var ?array<string, mixed> $additionalProperties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('additionalProperties')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $additionalProperties = null;

    /**
     *
     * @var ?string $imageUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $imageUrl = null;

    /**
     *
     * @var ?string $username
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('username')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $username = null;

    /**
     *
     * @var ?string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $label = null;

    /**
     * @param  ExternalAccountWithVerificationObject  $object
     * @param  string  $id
     * @param  string  $provider
     * @param  string  $identificationId
     * @param  string  $providerUserId
     * @param  string  $approvedScopes
     * @param  string  $emailAddress
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  array<string, mixed>  $publicMetadata
     * @param  int  $createdAt
     * @param  int  $updatedAt
     * @param  ?string  $avatarUrl
     * @param  Oauth|GoogleOneTap|null  $verification
     * @param  ?array<string, mixed>  $additionalProperties
     * @param  ?string  $imageUrl
     * @param  ?string  $username
     * @param  ?string  $label
     * @phpstan-pure
     */
    public function __construct(ExternalAccountWithVerificationObject $object, string $id, string $provider, string $identificationId, string $providerUserId, string $approvedScopes, string $emailAddress, string $firstName, string $lastName, array $publicMetadata, int $createdAt, int $updatedAt, ?string $avatarUrl = null, Oauth|GoogleOneTap|null $verification = null, ?array $additionalProperties = null, ?string $imageUrl = null, ?string $username = null, ?string $label = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->provider = $provider;
        $this->identificationId = $identificationId;
        $this->providerUserId = $providerUserId;
        $this->approvedScopes = $approvedScopes;
        $this->emailAddress = $emailAddress;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->publicMetadata = $publicMetadata;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->avatarUrl = $avatarUrl;
        $this->verification = $verification;
        $this->additionalProperties = $additionalProperties;
        $this->imageUrl = $imageUrl;
        $this->username = $username;
        $this->label = $label;
    }
}