<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


enum GoogleOneTapVerificationStrategy: string
{
    case GoogleOneTap = 'google_one_tap';
}
