<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Oauth
{
    /**
     *
     * @var OauthVerificationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OauthVerificationStatus')]
    public OauthVerificationStatus $status;

    /**
     *
     * @var string $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    public string $strategy;

    /**
     *
     * @var int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    public int $expireAt;

    /**
     *
     * @var ?string $externalVerificationRedirectUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_verification_redirect_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalVerificationRedirectUrl = null;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    public ?int $attempts;

    /**
     *
     * @var ?OauthErrorClerkError $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OauthErrorClerkError|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OauthErrorClerkError $error = null;

    /**
     *
     * @var ?string $verifiedAtClient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verified_at_client')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verifiedAtClient = null;

    /**
     * @param  OauthVerificationStatus  $status
     * @param  string  $strategy
     * @param  int  $expireAt
     * @param  ?string  $externalVerificationRedirectUrl
     * @param  ?int  $attempts
     * @param  ?OauthErrorClerkError  $error
     * @param  ?string  $verifiedAtClient
     * @phpstan-pure
     */
    public function __construct(OauthVerificationStatus $status, string $strategy, int $expireAt, ?string $externalVerificationRedirectUrl = null, ?int $attempts = null, ?OauthErrorClerkError $error = null, ?string $verifiedAtClient = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->expireAt = $expireAt;
        $this->externalVerificationRedirectUrl = $externalVerificationRedirectUrl;
        $this->attempts = $attempts;
        $this->error = $error;
        $this->verifiedAtClient = $verifiedAtClient;
    }
}